import os

MAX_FILES_TO_LOAD = 25

MAX_DOCS_TO_RETRIEVE = 5

MAX_DOCS_TO_PROCESS = 5

VECTOR_STORE_CACHE_SIZE = 32
EMBEDDING_CACHE_SIZE = 100

S3_TIMEOUT = 10
LLM_TIMEOUT = 30

DEBUG_MODE = False

FILE_LOADING_STRATEGY = "latest"
SMART_LOADING_KEYWORDS = ["lương", "bảo hiểm", "nghỉ phép", "tuyển dụng"]
